### PR TITLE
Also push for RHEL 9

### PR DESCRIPTION
**Pull request by Hipska**

### CODE REVIEW

**Comment by Hipska** [comment]
WDYT @Felixoid, @mchrome?

I can confirm the package from EL/8 works perfectly on a RHEL 9.

**Review by Felixoid — APPROVED** [review]
I'm not sure if it will work as expected.

In other words, does `el/9` exist?

**Comment by Hipska** [comment]
Surely it will, why wouldn't it?

See docs: https://packagecloud.io/docs#anchor-el

**Comment by Felixoid** [comment]
That was the question

**Pull request merged**
